 const MockJson =  {
     Column: [
        {name: "Country", width: 120},
        {name: "Capital", width: 120},
        {name: "ZipCode", width: 120},
        {name: "Continent", width: 120},
     ],
     Row:[
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"],
         ["Nigeria","Abuja",234,"Africa"],
         ["Ghana","Accra",233, "Africa"],
         ["Italy","Milan",187, "Europe"],
         ["China","Benjin",100,"Asia"],
         ["USA","Washington",123, "America"],
         ["Canada","Toronto",256, "America"],
         ["Mexico","Sample",279,"America"],
         ["india","Sample2",314, "Asia"],
         ["Sweeden","Sample4",101, "Europe"],
         ["Germany","Berlin",34,"Europe"],
         ["Russia","Sample5",127, "Europe"],
         ["Scotland","Sample6",212, "Europe"],
         ["Tazania","Sample7",271,"Africa"],
         ["Iraq","Sample8",433, "Asia"],
         ["Poland","Sample9",129, "Europe"]

         
     ]
}
export default MockJson;